# Generated by Django 5.0.2 on 2024-02-25 10:04

import lib.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='_persisted_id',
            field=lib.fields.VersionedBigIntegerField(null=True),
        ),
    ]
